### ISSUE TITLE
--configfile directory getting truncated? (v2.5)

### ISSUE THREAD

**Issue by kubu4** [blobtoolkit/insdc-pipeline#10]
Hi,

I'm attempting run the Snakemake command, but I keep getting the following error in the log file, `logs/busco/run_sub_pipeline.log`:

```python
Traceback (most recent call last):
  File "/gscratch/srlab/programs/anaconda3/envs/snakemake_env/bin/snakemake", line 10, in <module>
    sys.exit(main())
  File "/gscratch/srlab/programs/anaconda3/envs/snakemake_env/lib/python3.9/site-packages/snakemake/__init__.py", line 2620, in main
    success = snakemake(
  File "/gscratch/srlab/programs/anaconda3/envs/snakemake_env/lib/python3.9/site-packages/snakemake/__init__.py", line 506, in snakemake
    overwrite_config.update(load_configfile(f))
  File "/gscratch/srlab/programs/anaconda3/envs/snakemake_env/lib/python3.9/site-packages/snakemake/io.py", line 1599, in load_configfile
    config = _load_configfile(configpath)
  File "/gscratch/srlab/programs/anaconda3/envs/snakemake_env/lib/python3.9/site-packages/snakemake/io.py", line 1564, in _load_configfile
    obj = open(configpath_or_obj)
FileNotFoundError: [Errno 2] No such file or directory: '/gscratch/scrubbed/samwhite/outputs/config.yaml'

```

It indicates that my config file is not found at this location: `No such file or directory: '/gscratch/scrubbed/samwhite/outputs/config.yaml'`. And, that error is correct. My YAML file _isn't_ there. Here's the command I'm running:

```shell
#!/bin/bash
## Job Name
#SBATCH --job-name=20210519_pgen_blobtools_Panopea-generosa-v1.0
## Allocation Definition
#SBATCH --account=srlab
#SBATCH --partition=srlab
## Resources
## Nodes
#SBATCH --nodes=1
## Walltime (days-hours:minutes:seconds format)
#SBATCH --time=10-00:00:00
## Memory per node
#SBATCH --mem=500G
##turn on e-mail notification
#SBATCH --mail-type=ALL
#SBATCH --mail-user=samwhite@uw.edu
## Specify the working directory for this job
#SBATCH --chdir=/gscratch/scrubbed/samwhite/outputs/20210519_pgen_blobtools_Panopea-generosa-v1.0

# Set working directory
wd=$(pwd)

genome_fasta=${wd}/Panopea_generosa_v1.fasta

config="${genome_fasta##*/}_btk.yaml"

snakemake -p \
--use-conda \
--conda-prefix ${conda_dir} \
--directory ${wd}/ \
--configfile ${wd}/${config} \
--stats ${assembly_name}.snakemake.stats \
-j ${threads} \
--rerun-incomplete \
-s ${btk_pipeline}/blobtoolkit.smk \
--resources btk=1
```

I've set the variable `wd` to this value: `/gscratch/scrubbed/samwhite/outputs/20210519_pgen_blobtools_Panopea-generosa-v1.0`. However, it seems like the BUSCO command is looking at the directory above (`/gscratch/scrubbed/samwhite/outputs/`).

Is this a bug, or is there a change I can make to fix this?

Thanks for any help and I'm excited to finally give the v2.5 pipeline a go!

**Comment by rjchallis** [comment]
This isn't a bug, but it definitely needs to made clear in the readme. 

As the pipeline is split into a set of sub-pipelines, each one needs to run in a different subdirectory to keep the snakemakes separate. So where the previous pipeline ran in a single working directory that could be anywhere relative to the config file, for v2.5 each tool (including the `blobtoolkit.smk` meta-pipeline) needs to run in a subdirectory of the overall working directory. This top-level working directory has to contain a config file named config.yaml as it gets called separately for each sub-pipeline so this makes it simpler to keep track of.

So now instead of a uniquely named config file, each assembly needs a directory containing a config.yaml and as the various sub-pipelines are run, this directory fills up with subdirectories that share the snakefile names and `*.stats` files that serve to declare the sub pipeline to be complete. By the time the full pipeline is finished, this will look like:

```
$ cd $DATA_DIR/$ACCESSION
$ tree -L 1
.
├── blastn
├── blastn.stats
├── blobtoolkit
├── blobtoolkit.stats
├── blobtools
├── blobtools.stats
├── busco
├── busco.stats
├── config.yaml
├── diamond
├── diamond.stats
├── diamond_blastp
├── diamond_blastp.stats
├── minimap
├── minimap.stats
├── stats
├── stats.stats
├── view
├── view.stats
├── windowmasker
└── windowmasker.stats
```

The snakemake command to run the pipeline should look something like:
```
TOOL=blobtoolkit
snakemake -p \
          -j $THREADS \
          --directory $DATA_DIR/$ACCESSION/$TOOL \
          --configfile $DATA_DIR/$ACCESSION/config.yaml \
          --latency-wait 60 \
          --stats $DATA_DIR/$ACCESSION/$TOOL.stats \
          -s $SNAKE_DIR/$TOOL.smk
``` 

Each of the sub-pipelines can be run independently by just changing the value of `$TOOL`, which can be useful for debugging and is effectively what the `blobtoolkit.smk` pipeline does to run all the sub-pipelines. 

I've mostly been running this on open stack instances so at the moment this needs to run on a single cluster node. There is some control over the number of threads used by each sub-pipeline if you add a `settings.threads` section to your config. Defaults are equivalent to:

```
settings:
  threads:
    blastn: 30,
    blobtools: 4,
    busco: 30,
    diamond: 30,
    diamond_blastp: 30,
    minimap: 30,
    windowmasker: 1
```
